server:
  port: 18001
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://47.100.162.114:13306/etds?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      connection-test-query: SELECT 1
      validation-timeout: 3000
      read-only: false
      login-timeout: 5
  rabbitmq:
    host: 192.168.1.107
    password: 123456
    username: fecred
    port: 5672
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual


#mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#日志相关配置
logging:
  level:
    com.phadata.etdsplus.aspect: debug
    com.phadata.etdsplus: info
  file:
    #总日志文件，生成位置当前目录下的logs里面
    name: ./logs/chain.log
  logback:
    rollingpolicy:
      #服务重启清除历史日志，默认false
      clean-history-on-start: false
      #文件名，滚动生成，生成位置当前目录下的logs里面
      file-name-pattern: ./logs/chain.%d{yyyy-MM-dd}.%i.log
      #默认是7天，保存近30天
      max-history: 30
      #滚动日志每个文件大小的上限
      max-file-size: 6MB

## swagger 文档配置
knife4j:
  enable: true
  documents:
    - group: 1.0
      name: 错误码
      locations: classpath:md/** # 自定义文档
  setting:
    enableSwaggerModels: false
    enableDocumentManage: true
    enableHost: false
    enableHostText: http://192.168.0.254:8080
    enableRequestCache: true
    enableFilterMultipartApis: false
    enableFilterMultipartApiMethodType: POST
    language: zh-CN
    enableDebug: true
    enableSearch: false
    enableOpenApi: false
    enableAfterScript: false
    enableVersion: true
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright@2021-天机科技
  cors: false
  production: false # 是否正式环境
  basic:
    enable: false
    username: test
    password: 123


#关于鉴权中心配置
auth-center:
  #请求鉴权中心内置的key和secret
  app-key: c6ae6i06n88im0kpc92g
  secret: c6ae6i06n88im0kpc920
  #请求鉴权中获取token的地址
  get-token-url: 192.168.1.254:8080/api/v1/auth/token/create
  #请求鉴权中获取etds相关信息的地址
  get-etds-info-url: 192.168.1.254:8080/api/v1/auth/etds/activation-code
  #通知鉴权中心etds激活成功的地址
  notify-etds-activate-success: 192.168.1.254:8080/api/v1/auth/etds/activation-success

#关于凭证相关服务配置
dtc-server:
  #申请请求接口的rid
  apply-rid: http://192.168.1.106:8765/api/v1/dtc/registry/apply
  #创建凭证
  create-claim: http://192.168.1.106:8765/api/v1/dtc/registry/claim/create
  #验证凭证
  validate-claim: http://192.168.1.106:8765/api/v1/dtc/registry/claim/validate
  #注销凭证
  writeOff-claim: http://192.168.1.106:8765/api/v1/dtc/registry/claim/writeOff
  #服务接口密钥
  sKey: 6m4SNklr5eZspUjd
  #服务接口偏移量
  vKey: s5IUgjA9h2DWmFS8

#rabbitMQ发送配置
mq:
  send: http://192.168.1.111:4636/api/producer/send
